n = input()
p = int(input())
w = int(input())
m = int(input())
print("=" * 16 + "Чек" + "=" * 16)
print("Товар:" + " " * (29 - len(n)) + n)
print("Цена:" + " " * (19 - len(str(w)) - len(str(p))) + f"{w}кг * {p}руб/кг")
print("Итого:" + " " * (26 - len(str(w * p))) + f"{w * p}руб")
print("Внесено:" + " " * (24 - len(str(m))) + f"{m}руб")
print("Сдача:" + " " * (26 - len(str(m - w * p))) + f"{m - w * p}руб")
print("=" * 35)
